image: androidsdk/android-30

cache:
  paths:
  - .gradle/*

before_script:
  - apt install -y zip
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - yes | sdk install java 11.0.2-open

stages:
  - build
  - deploy

build-job:
  stage: build
  only:
  - branches
  script:
  - ./gradlew build :trail-conditions-app:lint :trail-conditions-app:bundle -PrunLint=true --no-daemon --console=plain
  artifacts:
    paths:
    - build/outputs/

deploy-job:
  stage: deploy
  script:
  - ./gradlew :trail-conditions-app:publishRelease --no-daemon --console=plain
  only:
  - master

